CarPlce/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarPlce.Models
{
    public class Car
    {
        public int Id { set; get; }
        [Required(ErrorMessage = "Не указан цвет авто")]
        public string Color { set; get; } //цвет авто
        [Required(ErrorMessage = "Не указан номер")]
        public string Number { set; get; } //номер
        [Required(ErrorMessage = "Не указан (date of create) - дата создания")]
        public DateTime Doc { set; get; } // (date of create) - дата создания
        [Required(ErrorMessage = "Не указан марка авто")]
        public string Mark { set; get; } // марка авто
        [Required(ErrorMessage = "Не указан модель авто")]
        public string Model { set; get; } // модель авто
        public int UserId { get; set; }  // Это свойство будет использоваться как внешний ключ
        public User User { get; set; } // связь один ко многим
    }
}

CarPlce/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CarPlce.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CarPlce.Controllers
{
    public class CarsController : Controller
    {
        private UsersContext db;
        public CarsController(UsersContext context)
        {
            db = context;
        }
        // GET: Cars
        public ActionResult Index()
        {
            // ViewBag.users = db.Users.ToList();
            // ViewBag.cars = db.Cars.ToList();
            ViewBag.cars = db.Cars.Include(r => r.User).ToList();  // Для загрузки связных данных
            return View();
        }
        [HttpGet] // метод добавления
        public ActionResult Add()
        {
            ViewBag.Users = new SelectList(db.Users, "Id", "Lastname"); //выподающий список
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Car car)
        {
            if (ModelState.IsValid)
            {
                // добавляем информацию в базу данных
                db.Cars.Add(car);
                // сохраняем в бд все изменения
                db.SaveChanges();
                return RedirectToAction("Index");
            }
                
            else
            return View(car);
        }
        [HttpGet] // метод редактирования
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.Users = new SelectList(db.Users, "Id", "Lastname");
            if (id != null)
            {
                Car car = await db.Cars.FirstOrDefaultAsync(p => p.Id == id);
                if (car != null)
                    return View(car);
            }
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit( Car car)
        {
            if (ModelState.IsValid)
            {
                db.Cars.Update(car);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
            return View(car);
        }
        [HttpGet] //метод удаления
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Car car = await db.Cars.FirstOrDefaultAsync(p => p.Id == id);
                if (car != null)
                    return View(car);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            {
                if (id != null)
                {
                    Car car = new Car { Id = id.Value };
                    db.Entry(car).State = EntityState.Deleted;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                return NotFound();
            }
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CarPlce/Views/Cars/Add.cshtml
@model CarPlce.Models.Car
@{
    Layout = null;
}
@{
    ViewData["Title"] = "Add";
}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | Add</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">

</head>
<div class="middle-box text-center loginscreen animated fadeInDown">
    <div>

        <h1 class="logo-name">IN+</h1>

    </div>
    <h3>Register to IN+</h3>
    <p>Create account to see it in action.</p>
    <form asp-action="Add" asp-controller="Cars" asp-anti-forgery="true">
        <div class="validation" asp-validation-summary="ModelOnly" />
        <div>
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
                <div class="form-group">
                    <input type="text" class="form-control" asp-for="Mark" placeholder="Mark">
                </div>

                <div class="form-group">
                    <input type="text" class="form-control" asp-for="Model" placeholder="Model">
                </div>

                <div class="form-group">
                    <input type="DateTime" class="form-control" asp-for="Doc" placeholder="Doc">
                </div>

                <div class="form-group">
                    <input type="text" class="form-control" asp-for="Number" placeholder="Number">
                </div>

                <div class="form-group">
                    <input type="text" class="form-control" asp-for="Color" placeholder="Color">
                </div>

                <div class="form-group">
                    <p>Владелец:</p>
                    @Html.DropDownList("UserId", ViewBag.Users as SelectList)
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Сохранить</button>

            }
        </div>
    </form>
</div>


<!-- Mainly scripts -->
<script src="~/js/jquery-2.1.1.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="~/js/plugins/iCheck/icheck.min.js"></script>
<script>
    $(document).ready(function () {
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });
</script>





@*

    @model CarPlce.Models.Car
    @{
        ViewData["Title"] = "Add";
    }
        <div>
            <h3>Добавление</h3>
            <p>Для добавления заполните следующие поля:</p>
            <form method="post">
                <input type="hidden" value="@ViewBag.CarId" name="CarId" />
                <div>
                    <label asp-for="Mark"></label><br />
                    <input type="text" asp-for="Mark" />
                    <span asp-validation-for="Mark"></span>
                </div>
                <div>
                    <label asp-for="Model"></label><br />
                    <input type="text" asp-for="Model" />
                    <span asp-validation-for="Model"></span>
                </div>
                <div>
                    <label asp-for="Doc"></label><br />
                    <input type="text" asp-for="Doc" />
                    <span asp-validation-for="Doc"></span>
                </div>
                <div>
                    <label asp-for="Number"></label><br />
                    <input type="text" asp-for="Number" />
                    <span asp-validation-for="Number"></span>
                </div>
                <div>
                    <label asp-for="Color"></label><br />
                    <input type="text" asp-for="Color" />
                    <span asp-validation-for="Color"></span>
                </div>
                    <div>
                        <td>Владелец:</td>
                        <td>@Html.DropDownList("UserId", ViewBag.Users as SelectList)</td>
                    </div>
                    <div>
                        <td><input type="submit" value="Сохранить" /></td>
                    </div>
            </form>
            @section scripts{

                <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
                <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
            }
        </div>

*@

CarPlce/Views/Cars/Delete.cshtml
@model CarPlce.Models.Car
@{
    Layout = null;
}
@{
    ViewData["Title"] = "ConfirmDelete";
}
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>INSPINIA | Delete</title>

        <link href="~/css/bootstrap.min.css" rel="stylesheet">
        <link href="~/css/plugins/iCheck/custom.css" rel="stylesheet">
        <link href="~/css/animate.css" rel="stylesheet">
        <link href="~/css/style.css" rel="stylesheet">

    </head>
<div>
    <h3>"Удаление"</h3>
</div>
<div class="middle-box text-center loginscreen animated fadeInDown">
    <dl class="dl-horizontal">
        <dt>Mark (марка):</dt>
        <dd>
            @Html.DisplayFor(model => model.Mark)
        </dd>
        <dt>Model (модель):</dt>
        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt>Date of create (Дата создания):</dt>
        <dd>
            @Html.DisplayFor(model => model.Doc)
        </dd>
        <dt>Number (номер):</dt>
        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt>Color (цвет авто):</dt>
        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>
    </dl>
    <div>
        <form asp-action="Delete" asp-controller="Cars" asp-anti-forgery="true">
            <!--<form asp-controller="Cars" asp-action="Delete" method="post">-->
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>
</div>

CarPlce/Views/Cars/Edit.cshtml
@model CarPlce.Models.Car
@{
    Layout = null;
}
@{
    ViewData["Title"] = "Edit";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | Register</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">

</head>
<div class="middle-box text-center loginscreen animated fadeInDown">
    <div>
        <h3>"Редактирование автомобиля"</h3>
    </div>

    <form asp-antiforgery="true" asp-action="Edit" asp-controller="Cars">
        <input type="hidden" value="@ViewBag.CarId" name="CarId" />
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="Mark" class="control-label">Mark (марка):</label>
            <input type="text" asp-for="Mark" class="form-control" />
            <span asp-validation-for="Mark"></span>
        </div>
        <div class="form-group">
            <label asp-for="Model" class="control-label">Model (модель):</label>
            <input type="text" asp-for="Model" class="form-control" />
            <span asp-validation-for="Model"></span>
        </div>

        <div class="form-group">
            <label asp-for="Doc" class="control-label">Date of create (Дата создания):</label>
            <input type="text" asp-for="Doc" class="form-control" />
            <span asp-validation-for="Doc"></span>
        </div>

        <div class="form-group">
            <label asp-for="Number" class="control-label">Number (номер):</label>
            <input type="text" asp-for="Number" class="form-control" />
            <span asp-validation-for="Number"></span>
        </div>

        <div class="form-group">
            <label asp-for="Color" class="control-label">Color (цвет авто):</label>
            <input type="text" asp-for="Color" class="form-control" />
            <span asp-validation-for="Color"></span>
        </div>
        <div>
            <td>Владелец:</td>
            <td>@Html.DropDownList("UserId", ViewBag.Users as SelectList)</td>
        </div>
        <div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary block full-width m-b">Сохранить</button>
            </div>
    </form>
</div>

<!-- Mainly scripts -->
<script src="~/js/jquery-2.1.1.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="~/js/plugins/iCheck/icheck.min.js"></script>
<script>
    $(document).ready(function () {
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });
</script>

CarPlce/Views/Cars/Index.cshtml
@model IEnumerable<CarPlce.Models.Car>
@{
    ViewData["Title"] = "Index";
}
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">

</head>

<div class="text-center">
    <h1 class="display-4">Car</h1>
</div>
<div>
    <div class="col-lg-3">

        @foreach (var car in ViewBag.cars)
        {
        <div class="contact-box">
            <h6>Mark (марка): @car.Mark</h6>
            <h6>Model (модель): @car.Model</h6>
            <h6>Date of create (Дата создания): @car.Doc</h6>
            <h6>Number (номер): @car.Number</h6>
            <h6>Color (цвет авто): @car.Color</h6>
            <a class="btn btn-sm btn-white btn-block" asp-action="Edit" asp-controller="Cars" asp-route-id="@car.Id">Изменить</a>
            <a class="btn btn-sm btn-white btn-block" asp-action="Delete" asp-controller="Cars" asp-route-id="@car.Id">Удалить</a>

            <!-- Вызов связных данных из класса User -->
            <div class="contact-box">
                <h6>Owner (Владелец): @car.User.Firstname @car.User.Lastname</h6>
                <table>
                    <tr>
                        <a asp-action="Edit" asp-controller="Users" asp-route-id="@car.Id">Изменить</a>
                    </tr>
                </table>
            </div>
        </div>
            
        }
    </div>

</div>


<div>
    <table>
        <tr>
            <td><p><a class="btn btn-sm btn-white btn-block" href="Add">Добавить</a></p></td>
        </tr>
    </table>
</div>

<!-- Mainly scripts -->
<script src="~/js/jquery-2.1.1.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="~/js/plugins/iCheck/icheck.min.js"></script>
<script>
    $(document).ready(function () {
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });
</script>






@*
    @foreach (var user in ViewBag.users)
    {
        <div class="contact-box">
            <h6>Owner (Владелец): @user.Firstname @user.Lastname</h6>
            <table>
                <tr>
                    <a asp-action="Edit" asp-controller="Users" asp-route-id="@user.Id">Изменить</a>
                </tr>
            </table>
        </div>
    }
*@